# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_from', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sum_in_words', models.CharField(max_length=50)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=38)),
                ('total_sales_vat_inclusive', models.DecimalField(decimal_places=2, max_digits=38)),
                ('less_vat', models.DecimalField(decimal_places=2, max_digits=38)),
                ('total', models.DecimalField(decimal_places=2, max_digits=38)),
                ('less_sc_pwd_disc', models.DecimalField(decimal_places=2, max_digits=38)),
                ('less_withholding_tax', models.DecimalField(decimal_places=2, max_digits=38)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=38)),
                ('vatable_sales', models.DecimalField(decimal_places=2, max_digits=38)),
                ('vat_exempt_sales', models.DecimalField(decimal_places=2, max_digits=38)),
                ('vat_zero_rated_sales', models.DecimalField(decimal_places=2, max_digits=38)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=38)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=38)),
                ('is_full', models.BooleanField(default=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Identity_Information')),
            ],
        ),
    ]
