# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Civil_Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Identity_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Mid_Name', models.CharField(default='', max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Home_Address', models.CharField(max_length=300)),
                ('Personal_Phone', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(upload_to='')),
                ('Occupation', models.CharField(default='None', max_length=100)),
                ('Office_Address', models.CharField(default='None', max_length=300)),
                ('Employer', models.CharField(default='None', max_length=100)),
                ('Office_Phone', models.CharField(default='None', max_length=50)),
                ('Civil_StatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Civil_Status')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabReport', models.TextField(max_length=180)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabType', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nursing_Record', models.TextField(max_length=180)),
                ('NR_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UO_Date_of_operation', models.DateField(default='')),
                ('Operation_RoomNo', models.IntegerField(default='')),
                ('Duration_of_operation', models.TimeField(default='')),
                ('AssessmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Operational_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Ops_Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_Room_Rec', models.TextField(max_length=180)),
                ('OR_Date_of_Operation', models.DateField()),
                ('Ops_Rec_RoomNo', models.IntegerField()),
                ('Operational_RecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Operational_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Physician_Exam', models.TextField(max_length=300)),
                ('Chief_Complaint', models.TextField(max_length=300)),
                ('History_of_present_illness', models.TextField(max_length=300)),
                ('Attending_Physician', models.CharField(max_length=180)),
                ('Date', models.DateField()),
                ('AssessmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('NCE', models.CharField(default='None', max_length=50)),
                ('Relationship_to_NCE', models.CharField(default='None', max_length=50)),
                ('Identity_InformationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Identity_Information')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Assessment', models.TextField(max_length=180)),
                ('Treatment', models.TextField(max_length=180)),
                ('Patient_HistoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Patient_History')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Religion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concern', models.TextField(max_length=180)),
                ('Setup_Time', models.TimeField()),
                ('Setup_Date', models.DateField()),
                ('Requested_Date', models.DateField()),
                ('Requested_Time', models.TimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Schedule_Information')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('image', models.FileField(default='null', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Service_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anesthesia_Record', models.CharField(max_length=180)),
                ('AR_Date', models.DateField()),
                ('Other_Intake', models.CharField(max_length=180)),
                ('OI_Date', models.DateField()),
                ('Operational_RecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Operational_Record')),
            ],
        ),
        migrations.AddField(
            model_name='nurse_record',
            name='Operational_RecordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Operational_Record'),
        ),
        migrations.AddField(
            model_name='lab_report',
            name='Lab_TypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Lab_Type'),
        ),
        migrations.AddField(
            model_name='lab_report',
            name='Patient_HistoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Patient_History'),
        ),
        migrations.AddField(
            model_name='identity_information',
            name='NationalityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Nationality'),
        ),
        migrations.AddField(
            model_name='identity_information',
            name='ReligionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Religion'),
        ),
        migrations.AddField(
            model_name='identity_information',
            name='SexID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Sex'),
        ),
        migrations.AddField(
            model_name='identity_information',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Patient_InfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Patient_Information'),
        ),
    ]
